SELECT * 
FROM Person.Address
WHERE CITY LIKE 'P%'
ORDER BY CITY

SELECT * 
FROM Person.Address
WHERE CITY LIKE '%A'
ORDER BY CITY

SELECT * 
FROM Person.Address
WHERE CITY LIKE '_L%'
ORDER BY CITY
